### ISSUE TITLE
incorrect work with ACL

### ISSUE THREAD

**Issue by iWildStyle** [cosmocode/virtualgroup#17]
Hi.
I have a problem:
User **user1** included in virtual group **@group1**.
In ACL manager I set up rights: for namespace **some:namespace:**\* and group **@group1** - **Delete** (i.e. full access), for root namespace \* and group **@user** (default group) - **Read**

Then, when I check right for namespace **some:namespace:**\* and group **@group1** I get correct rights - **Delete**. But when I check right for namespace **some:namespace:**\* and user **user1** I get incorrect rights - **Read**

**Comment by einhirn** [comment]
How do you check rights?
When you do a "do=check" when logged in as "user1" what groups are there listed? If "group1" is listed everything is fine. This plugin just changes the list of groups a user belongs to, on the fly and bypassing auth plugins. The ACL checks still are stock Dokuwiki, this plugin doesn't change them at all.

**Comment by splitbrain** [comment]
no feedback given
