### ISSUE TITLE
 Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by ersft** [cosmocode/virtualgroup#25]
Freshly installed the plugin, throws error below the Add Group fieldset.
`Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\lib\plugins\virtualgroup\admin.php on line 395`

Added users are listed, but not persistently. An error is display at the top of the page:
`Warning: file_put_contents(\data/virtualgrp.php): failed to open stream: No such file or directory in C:\xampp\htdocs\lib\plugins\virtualgroup\admin.php on line 253`

virtualgrp.php has not been created on install and creating it manually didn't help either.

The user disappears from the table on reload. Another error shows up when I press edit:
`Warning: implode(): Invalid arguments passed in C:\xampp\htdocs\lib\plugins\virtualgroup\admin.php on line 337`

Thanks.

**Comment by splitbrain** [comment]
should be fixed with recent release
